version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: dbs2webapp.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080;https://+:8081"
    networks:
      - web

  client:
    build:
      context: .
      dockerfile: dbs2webapp.Client/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - web

networks:
  web:
    driver: bridge
